service: aws-gruppexamination-smooth-gardeners
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:PROFILE}
  region: eu-north-1
  iam:
    role: ${env:LAMBDA_ROLE}
  deploymentMethod: direct
  environment:
    TABLE_NAME: bookings

useDotenv: true

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    webpackConfig: 'webpack.config.cjs'

functions:
  getBooking:
    handler: src/functions/getBooking.handler
    events:
      - httpApi:
          path: '/api/booking'
          method: GET
  getBookings:
    handler: src/functions/getBookings.handler
    events:
      - httpApi:
          path: '/api/bookings'
          method: GET
  postBooking:
    handler: src/functions/postBooking.handler
    events:
      - httpApi:
          path: '/api/booking'
          method: POST
  updateBooking:
    handler: src/functions/updateBooking.handler
    events:
      - httpApi:
          path: '/api/booking'
          method: PATCH
  deleteBooking:
    handler: src/functions/deleteBooking.handler
    events:
      - httpApi:
          path: '/api/booking'
          method: DELETE

resources:
  Resources:
    BonzaiDatabase:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: StartDate
            AttributeType: S
          - AttributeName: EndDate
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: StartDate
                KeyType: HASH
              - AttributeName: EndDate
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
